security:
    password_hashers:
        app_hasher:
            id: src\Common\Infrastructure\Symfony\Security\YiiPasswordHasher
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user_provider:
            id: src\Common\Infrastructure\Symfony\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        biz:
            request_matcher: firewall_biz_request_matcher
            lazy: true
            provider: user_provider
            form_login:
                login_path: /user/signup
                check_path: /user/login
            logout:
                path: /user/logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000
                always_remember_me: true
        public:
            security: false

    access_control:
        - { request_matcher: access_control_biz_public_request_matcher, roles: [ PUBLIC_ACCESS ] }
        - { path: '^/', roles: [ IS_AUTHENTICATED ] }